### ISSUE TITLE
Use optimized protobuf parsing/writing

### ISSUE THREAD

**Issue by JanecekPetr** [HebiRobotics/QuickBuffers#14]
I took a look at this project and am interested in trying it out. Before that, I also looked at your benchmarks, and while I agree that their code is the most idiomatic one, it's definitely not the fastest one possible. For example, there's a trick for faster protobuf parsing: https://stackoverflow.com/questions/21854687/improving-performance-of-protocol-buffers/21870564#21870564

> Instead of using `readDelimitedFrom()`, construct a single `CodedInputStream` and use it to read multiple messages like so:
> 
> ```
> // Do this once:
> CodedInputStream cis = CodedInputStream.newInstance(input);
> 
> // Then read each message like so:
> int limit = cis.pushLimit(cis.readRawVarint32());
> builder.mergeFrom(cis);
> cis.popLimit(limit);
> cis.resetSizeCounter();
> ```

Similarly, when throughput is actually critical, we're not writing protobufs one-by-one, creating a `CodedOutputStream` for every object. We create a single `CodedOutputStream` and write as many objects into it as possible in a loop / until a buffer is full:

```
codedOutputStream.writeUInt32NoTag(message.getSerializedSize());
message.writeTo(codedOutputStream);
```

Would you be interested in accepting a PR adding benchmarks with these? Do you think we can improve the current benchmarks? Or do you perhaps think such benchmarks would not be representative?

**Comment by ennerf** [comment]
Thanks for the feedback. The "File Streams" benchmark uses a single `CodedInputStream` and `CodedOutputStream` object ([SbeBenchmark](https://github.com/HebiRobotics/QuickBuffers/blob/master/benchmarks/src/main/java/us/hebi/quickbuf/benchmarks/comparison/SbeBenchmark.java#L230-L245)) for ~70-150k messages in the way you're describing.

The "SBE dataset" benchmark you're referring to was intentionally kept using the same code as the comparison in [SBE](https://mechanical-sympathy.blogspot.com/2014/05/simple-binary-encoding.html) after Kenton Varda's improvements. For now I'd prefer to keep it as is.

Overall, the impact of this should be relatively minor. I think much bigger gains would come from constructing messages back to front, so that the size doesn't have to be pre-calculated everywhere. I haven't had time to fully implement it yet, but initial tests look like encoding speed could improve by another 20-50% depending on the use case.

If you do end up testing it, I'd be very interested in how the numbers on your actual system change.

**Comment by JanecekPetr** [comment]
Oh! I missed that part of the code, thank you. Much appreciated, I think it's safe to close this issue now.

I know the issue of precalculating the size, but do not see how back-to-front message construction would help. I'll think about that.

**Comment by ennerf** [comment]
If you write a message backwards, you know the size without having to calculate it. For example, writing a nested message is

```Java
writeTag(number << 3 | length_delimited);
writeLength(nestedMsg.getSerializedSize());
writeMessage(nestedMsg);
```

this could be replaced with

``Java
int start = position();
writeMessage(nestedMsg);
writeLength(start - position());
writeTag(number << 3 | length delimited);
```

When encoding the market/car messages the cost roughly splits as 33% constructing the message, 33% pre-calculating the size, and 33% encoding it on the wire. So far cases where it's simply forwarding a decoded message, you could save almost 50%.

Another way could be to leave enough space for the maximum size (all fields set and all 4 byte UTF8 chars and 5 byte ints) and to fill it in later (varint with the top bits zero).

**Comment by JanecekPetr** [comment]
> So far cases where it's simply forwarding a decoded message, you could save almost 50%.

This is indeed something that hurts us: https://github.com/protocolbuffers/protobuf/issues/5729

Oh well. I will take a look sooner or later. Thanks for the project!

**Comment by ennerf** [comment]
Interesting read. The [comment ](https://github.com/protocolbuffers/protobuf/issues/5729#issuecomment-467224025) lists the same approaches I mentioned, so that's a good confirmation. Always using fixed 4 byte varints (28 bit) for every length delimited value would be pretty simple to implement.

If you know that your input source is well formed and that the message is cleared before merging, you could add your current "hack" by adding `msg.cachedSize = length` after [ProtoSource#L433](https://github.com/HebiRobotics/QuickBuffers/blob/master/runtime/src/main/java/us/hebi/quickbuf/ProtoSource.java#L433-L434). If the cached size > 0, it will use it when calling `writeMessage`.

(`read/write Message` are basically identical to `read/write Delimited()`)

**Comment by ennerf** [comment]
What's your reason for not just storing the already-serialized bytes btw.? For example,

```Java
// read delimited message in raw byte form
int length = readRawVarint32FromInputStream(input);
byte[] bytes = readNBytes(input, length);

// decode to filter message
msg = parseFromBytes(bytes);
if(satisfiesSomeCondition(msg)) {

   // write delimited message (already serialized)
   writeRawVarint32ToOutputStream(output, length);
   writeNBytes(output, bytes, length);

}
```

`ProtoUtil` contains [helper functions](https://github.com/HebiRobotics/QuickBuffers/blob/master/runtime/src/main/java/us/hebi/quickbuf/ProtoUtil.java#L38-L114) for reading/writing varint32 from streams.

**Comment by ennerf** [comment]
After a bit more debugging, it turns out that a significant part of the clear/compute-size cost came from the `cachedSize` being `volatile`. Making it a normal variable improves encoding of the market message by almost 60%.

I also tried unrolling the varint32/64 loops which would be necessary for encoding back-to-front, but I saw as much as 30% performance degradation on the market-message, even though it's using few varints. That's more overhead than what it could potentially save, so that's probably a dead end.

**Comment by JanecekPetr** [comment]
> What's your reason for not just storing the already-serialized bytes btw.?

This is indeed something we're considering, but, as always, things aren't that simple. First of all, the original message is a slice of a direct `ByteBuffer`, so we'd need to materialize all that memory into the Java heap. Second of all, *sometimes* the protobuf needs to be changed a little - a timestamp for a timestamp. The size of the field is fixed, but we're not able to do the change in-place.

Still, indeed, this might be a net win, I do not know yet, the problem is not *that* critical, just annoying. Will prod around all this again, and will monitor this library for further development :)

**Comment by ennerf** [comment]
You could set `store_unknown_fields=true` and define a .proto that only contains the fields that you may need to modify. Unknown fields get stored as raw bytes, so they can be re-serialized very efficiently.

I assume that for some scalar fields it may be cheaper to parse and serialize (haven't tested), but for length delimited fields (packed, strings, nested messages, etc.) you should be able to see a good speedup.

I'm pretty much done with what I wanted in the library. I may still add a way to deserialize JSON and add support for services, but both are low priority. Other than that don't expect too much more additional feature development. 

If you get a chance to test it, I'd appreciate feedback on the API. Now it's still easy to change if some parts t urn out awkward to use.

**Comment by ennerf** [comment]
Another thought: Assuming correct decoding implementation, if a message contains the same field multiple times, the last one will overwrite any previous entries. So technically you can copy the bytes of the original message, and then append a "delta" that contains any changes. This works for any non-repeated field (repeated just get appended), even in nested messages.

Below is some pseudo code 

```Java
void doSomething(Message original, Message delta){
   if(original.getTimestamp == badTimestamp) {
    delta.setTimestamp(goodTimestamp);
  }

output.writeVarint(originalBytes + delta.getSerializedSize());
output.write(originalBytes);
output.write(delta);

}
```


The decoder will pay a bit of overhead in parsing a field twice, but your serialization becomes practically free.

**Comment by JanecekPetr** [comment]
> you can copy the bytes of the original message, and then append a "delta"

Now this, sir, is worth a thousand points. Seems obvious in hindsight. Thank you, this elegantly solves our problem in this part of the application. I'm buying you a beer every time you'll be in Prague, Czech Republic.

We'd still profit hugely from QuickBuffers elsewhere, we'll get to some real-world tests soon.

Thank you!

**Comment by ennerf** [comment]
I'm glad I could help. I'm in Prague every once in a while, so I may call you up on that :)
