### ISSUE TITLE
usage scenarios

### ISSUE THREAD

**Issue by liangsir12** [HebiRobotics/QuickBuffers#59]
Hello, I would like to convert protobuf to JSON now, but I find that the performance of the built-in tool from Google is not satisfactory. Can this project help me improve the conversion efficiency?

**Comment by ennerf** [comment]
It depends a bit on the details, but the answer is very likely yes.

**Comment by juja0** [comment]
Will the generated json be spec compatible ? The docs seem to suggest that special casing of well-known types is not implemented and I don't see it in generateWriteToJson method either. Is it worth adding a way to customize (via some plugin architecture) the way the java sources are generated in message generator (atleast the generateWriteToJson and generateMergeFromJson methods)  ? Or will that add maintenance issues down the line ?

**Comment by ennerf** [comment]
The spec is compatible except for `long` types (serialized as json number, so integers above 53 bit may lose precision when parsed as double), and the special-cased proto3 types like `Any`, `Duration`, and `Timestamp`.

I've never needed the well-known types, but I think this could be added by (1) adding appropriate read/write methods to the json source/sink, or by (2) adding pre-generated types to the runtime library that implement the special behavior.

Doing some plugin architecture sounds difficult, but I haven't looked into how the protobuf-java extension points work.

**Comment by juja0** [comment]
Wouldn't "Struct" being a special-case make (2) not a viable option ?

I was evaluating quick-buffers as a replacement for google's proto-util and it didn't work for a specific use-case that I was trying it for, since it had a struct field which could have an arbitrary shape.

I didn't quite understand your statement about protobuf-java extension points. I was referring to adding extension points in the class MessageGenerator.java in the quick-buffers repository since I was under the assumption that that's the one responsible for generating the java files. 

If there's any specific way you think this should be done, I am to happy to give it a shot and submit a PR for this.

**Comment by juja0** [comment]
> Do you have an example of one being serialized as JSON?

Been a while since I tried it, so created a unit test to confirm. Here's a [link](https://github.com/juja0/QuickBuffers/blob/123e22fec6f81a943b6c093372e4a816bab549dc/runtime/src/test/java/us/hebi/quickbuf/JsonSinkTest.java#L333) to the relevant section.

The test starts with a simple json string and tests if a roundtrip deserialization + serialization produces the same json.

This works for 

- protobuf RootMessage (proto definition in link) deser + ser 
- protobuf Struct deser + ser 
- quickbuf RootMessage deser + ser 

but fails for both deserialization and serialization of quickbuf Struct

**Comment by liangsir12** [comment]
My scenario is that there are only proto files with thousands of lines of fields, so I don't want to write corresponding Java POJO classes. But I am not only connected to protobuf, but also to JSON, so I need to return both protobuf and JSON formats, and I need to convert protobuf to JSON. This framework seems to meet my needs very well, and I have tried it out. It seems that the toString method of the Java class generated from the proto file directly returns JSON? Do I need to write it back into the byte array and then use the original protoBuf to parse from the byte array? Like this:
![image](https://github.com/HebiRobotics/QuickBuffers/assets/122345297/ee37b7c1-47d2-49c2-b5cd-ce8cffe15020)
Or can I simply return quickBuffers?
![image](https://github.com/HebiRobotics/QuickBuffers/assets/122345297/7c7ecea2-fa35-4cd3-a1c4-20fd40a6f986)
And I also have a question. In my scenario, will quickBuffers be much faster from assigning values (thousands of fields) to returning than protoBuff assigning values to converting to JSON? I gave it a simple try, as quickBuffer does not need to convert to JSON, so the time is much shorter.

**Comment by juja0** [comment]
> it'd be best if you could add `read/write` `Timestamp/Duration/Struct?` methods to the JsonSource/JsonSink

I took a look at what needs to be done to add the read and write methods and I think I know where to start. But just to be clear, we currently just want these read/write methods to be added to the Json source and sink but they will not be used by the generator or any other code for that matter ? And that will be implemented later ? 

If so, I think I'd like to add the read/write methods as two separate PRs. The first one would be just for Timestamp and Duration since they seem to be fairly straightforward. Once that's merged, I can start working on adding read/write methods for struct.

**Comment by ennerf** [comment]
You can write JSON to a `RepeatedByte` (reusable growing `byte[]`) using `JsonSink`. It also provides more options on pretty printing (added whitespace) and enum formatting.

> I took a look at what needs to be done to add the read and write methods and I think I know where to start. But just to be clear, we currently just want these read/write methods to be added to the Json source and sink but they will not be used by the generator or any other code for that matter ? And that will be implemented later ?

Yes, that matches what I'm thinking. Off the top of my head I think it's possible to add the special casing via a simple overload, e.g.,

```Java
Proto3JsonSink extends DefaultJsonSink {
  @Override
  public void writeMessage(ProtoMessage<?> msg) {
    if (msg instance Timestamp) {
    writeTimestamp(msg.getValue()); // (it shouldn't reference the actual message type)
  } else {
    super.writeMessage(msg);
  }
}
```

That'd allow you do test everything locally without changes to the library. Once everything works we can pre-generate special-cased classes that are bundled in the jar and get referenced by the code generator. The only methods needed for that should be the extra read/write methods on JsonSource/Sink.

**Comment by juja0** [comment]
> it should be possible to add the special casing via a simple overload in your local code

This looks interesting. I think this should work for us. 

> Once everything works we can pre-generate special-cased classes.

Sounds good. Will implement this in our application and see how it works.

**Comment by ennerf** [comment]
Did you manage to get it working?

**Comment by juja0** [comment]
@ennerf I missed the previous message. Yes I did try out your suggestion and it worked great for serialization, although I'm still unsure how to get deserialization to work by just modifying the jsonSource (without modifying the generated classes in some way). 

For reference, this is a very crude implementation of a custom jsonSink with basic support for struct (haven't tested deeply nested structures yet)

```

	private static JsonSink newCustomJsonSink()
	{
		return new JsonSink.DefaultJsonSink()
		{
			@Override
			public JsonSink writeMessage(ProtoMessage<?> value) throws IOException
			{
				if (value instanceof Struct)
				{
					Struct struct = (Struct) value;

					this.beginObject();

					for (Struct.FieldsEntry field : struct.getFields())
					{
						FieldName fieldName = FieldName.forField(field.getKey());

						Value fieldValue = field.getValue();

//						this.writeFieldName(fieldName);
//						fieldValue.writeTo(this);

						if (fieldValue.hasNumberValue())
						{
							this.writeDouble(fieldName, fieldValue.getNumberValue());
						}
						if (fieldValue.hasNullValue())
						{
							this.writeEnum(fieldName, fieldValue.getNullValueValue(), NullValue.converter());
						}
						if (fieldValue.hasBoolValue())
						{
							this.writeBool(fieldName, fieldValue.getBoolValue());
						}
						if (fieldValue.hasStructValue())
						{
							this.writeMessage(fieldName, fieldValue.getStructValue());
						}
						if (fieldValue.hasListValue())
						{
							this.writeMessage(fieldName, fieldValue.getListValue());
						}
						if (fieldValue.hasStringValue())
						{
							this.writeString(fieldName, fieldValue.getStringValue());
						}
					}

					this.endObject();

					return this;
				}
				else
				{
					return super.writeMessage(value);
				}
			}
		}.setOutput(RepeatedByte.newEmptyInstance());
	}

```

But when using a custom jsonSource, I wasn't able to figure out how to get something like 

``` Struct.parseFrom(newCustomJsonSource(jsonString)) ``` to work, since the Struct would be expecting the 'jsonString' to be in a different structure and not a vanilla json.


In the original testcase that I attached in one of my previous messages, there were two failing assertions, one for deserialization and one for serialization. With the above custom json sink, the serialization assertion passes but the deserialization assertion still fails. I haven't made any progress after that.

**Comment by ennerf** [comment]
I'm not entirely clear on how to best add it either. Given that you've solved the problem externally for now, I'll close this issue.
